accounts/urls.py
from django.urls import path, include

from accounts import views

app_name = "accounts"

urlpatterns = [
    path("test/", views.test, name="test"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

from catalog import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("__debug__/", include("debug_toolbar.urls")),
    # path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls", namespace="user")),
    path("api/v1/catalog/", include("catalog.urls_api", namespace="catalog_api")),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse


@login_required
def test(request: HttpRequest) -> HttpResponse:
    return HttpResponse("<h1>Test</h1>")


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        return render(request, "accounts/login.html")
    elif request.method == "POST":
        print(f"request data: {request.POST}")
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("catalog/index"))
        else:
            error_context = {"error": "Invalid credentials"}
            return render(request, "registration/login.html", context=error_context)


@login_required
def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return render(request, "registration/logged_out.html")

templates/accounts/logged_out.html
{% extends "base.html" %}

{% block content %}
  <p>Logout success</p>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <h1>Login:</h1>
  {% if error %}
    <p style="color: red"><strong>{{ error }}</strong></p>
  {% endif %}
  <form action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}
    <label>Username
      <input type="text" name="username">
    </label>
    <br>
    <label>Password
      <input type="password" name="password">
    </label>
    <br>
    <input type="submit" value="Submit">
  </form>
{% endblock %}